version: '2'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    build:
      context: ./compose/postgres
      dockerfile: Dockerfile-pg
    shm_size: 512m
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./data:/data
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"

  django:
    build:
      context: ./
      dockerfile: ./compose/django/Dockerfile-dj
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=toor
      - USE_DOCKER=yes
      - DATABASE_URL
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django

