services:
  db:
    build:
      context: ./compose/db/
      dockerfile: Dockerfile-pg
    shm_size: 512m
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}" ]
      interval: 1s
      retries: 10

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - api

  web:
    build:
      context: ./
      dockerfile: ./compose/web/Dockerfile-dj
    command: /start-dev.sh
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    env_file:
      - .env
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    networks:
      - api

  nginx:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - api

networks:
  api:
    name: "api"
